/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    'Fa6Solid:heartPulse': typeof import('~icons/fa6-solid/heart-pulse')['default']
    HomePage: typeof import('./theme/components/HomePage.vue')['default']
    Hyperlinks: typeof import('./theme/components/Hyperlinks.vue')['default']
  }
}
